version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: order-service
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: order-service